apiVersion: v2
name: kyverno-policies-connectivity
version: 0.9.2-dev
appVersion: 0.9.2-dev
description: Giant Swarm policies for connectivity management.
home: https://github.com/giantswarm/kyverno-policies-connectivity
icon: https://s.giantswarm.io/app-icons/kyverno/1/light.svg
annotations:
  io.giantswarm.application.team: "cabbage"
  config.giantswarm.io/version: 1.x.x
